# Generated by Django 5.2 on 2025-04-28 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('email_address', models.EmailField(max_length=254)),
                ('num_spam', models.IntegerField(default=0)),
                ('total_appearance', models.IntegerField(default=0)),
                ('is_spam', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'global_users',
            },
        ),
    ]
