# Generated by Django 5.2 on 2025-04-28 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='globaluser',
            old_name='is_spam',
            new_name='spam_likelyhood',
        ),
        migrations.AlterField(
            model_name='globaluser',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='globaluser',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
