# Generated by Django 5.2 on 2025-04-28 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_is_spam_globaluser_spam_likelyhood_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalContacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_from', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_to', models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                'db_table': 'global_contacts',
            },
        ),
    ]
